### ISSUE TITLE
Implement Drink

### ISSUE THREAD

**Issue by maxstolze** [maxstolze/fizz#1]
- [x] Types
- [x] Actions
- [x] DB
- [x] API & PHP
- [x] GUI
- [x] Tests

**Comment by GeorgManusch** [comment]
Kannst du bei der Tabelle, zum einfügen von Drinks, ne Funktion mit einbauen, dass ich für die markierten Zellen die gleiche "Funktion" haben will.
Also ich markiere A2 bis A8 und will in allen Zellen die Zahl 8 haben
