### ISSUE TITLE
Implement Drink

### ISSUE THREAD

**Issue by GeorgManusch** [maxstolze/fizz#24]
Kannst du bei der Tabelle, zum einfügen von Drinks, ne Funktion mit einbauen, dass ich für die markierten Zellen die gleiche "Funktion" haben will.
Also ich markiere A2 bis A8 und will in allen Zellen die Zahl 8 haben

**Comment by maxstolze** [comment]
Duplicate of Issue #1

**Comment by maxstolze** [comment]
As comment in #1
